# Generated by Django 3.2.8 on 2021-12-10 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='t_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tt_from', to=settings.AUTH_USER_MODEL),
        ),
    ]
