# Generated by Django 3.2.8 on 2021-12-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transact', '0003_auto_20211210_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='memo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='memo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
